[project]
name = "hello-world"
version = "0.1.0"
description = "A Hello World application in Python."
authors = [
    { name = "sce-taid", email = "sce@taid.me" }
]
license = { text = "Apache-2.0" }
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "Flask>=3.0.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
