#!/bin/bash

# Copyright 2025-2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail

export XDG_SESSION_TYPE=x11
export XKL_XMODMAP_DISABLE=1

export DESKTOP_SESSION=ubuntu-xorg
export XDG_SESSION_DESKTOP="$DESKTOP_SESSION"
export XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu-xorg:/etc/xdg
export XDG_CURRENT_DESKTOP=ubuntu:GNOME
export XDG_DATA_DIRS="/usr/share/$DESKTOP_SESSION:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop"
export GNOME_SHELL_SESSION_MODE=ubuntu

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

if [[ -x /etc/vnc/xstartup ]]; then
  exec /etc/vnc/xstartup
fi

if [[ -r "$HOME/.Xresources" ]]; then
  xrdb "$HOME/.Xresources"
fi

vncconfig -nowin &
exec dbus-launch --exit-with-session gnome-session
