# Copyright 2023-2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: skaffold-build
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Build Tools
    tekton.dev/tags: build-tool
    tekton.dev/displayName: "skaffold build"
    tekton.dev/platforms: "linux/amd64"
spec:
  workspaces:
  - name: workspace
    description: The workspace containing the source code for the build conducted by Skaffold

  params:
    - name: git-url
      description: The URL of the git repository to clone from.
      type: string

    - name: application-path
      type: string
      description: The path within the git repository to the application hosting the skaffold.yaml.

    - name: registry
      type: string
      description: The container registry to use. This is used by Skaffold.

    - name: verbosity
      type: string
      description: The verbosity level to use when executing the tasks.
      default: warning

  tasks:
  - name: git-clone
    taskRef:
      name: git-clone
    params:
    - name: url
      value: $(params.git-url)
    - name: verbose
      # TODO: evaluate to `true` or `false`
      value: $(params.verbosity)
    workspaces:
    - name: output
      workspace: workspace

  - name: skaffold-build
    taskRef:
      name: skaffold-build
    runAfter:
    - git-clone
    params:
    - name: PATH
      value: $(params.application-path)
    - name: SKAFFOLD_VERBOSITY
      value: $(params.verbosity)
    - name: SKAFFOLD_DEFAULT_REPO
      value: $(params.registry)
    workspaces:
      - name: source
        workspace: workspace
